'use strict';
const $=id=>document.getElementById(id),money=n=>new Intl.NumberFormat('tr-TR',{style:'currency',currency:'TRY'}).format(n/100);
const el=(tag,text)=>{const x=document.createElement(tag);if(text!==undefined)x.textContent=text;return x;};
let items=[],selected=null,requestId=null,busy=false;
async function api(path,body){const r=await fetch(path,{method:body?'POST':'GET',headers:{'X-Ogun-Lab':'1',...(body?{'Content-Type':'application/json'}:{})},body:body?JSON.stringify(body):undefined});const j=await r.json();if(!r.ok)throw Error(j.error||'İstek başarısız');return j;}
function render(){const q=$('search').value.toLocaleLowerCase('tr-TR');$('rows').replaceChildren();for(const x of items.filter(x=>(x.name+' '+x.branch+' '+x.category).toLocaleLowerCase('tr-TR').includes(q))){const tr=el('tr');tr.append(el('td',x.name),el('td',x.branch),el('td',money(x.price_minor)));const td=el('td'),b=el('button','Fiyatı değiştir');b.onclick=()=>{selected=x;requestId=crypto.randomUUID();$('mealTitle').textContent=x.name;$('oldPrice').textContent='Mevcut fiyat: '+money(x.price_minor);$('price').value=x.price_minor/100;$('error').textContent='';$('priceDialog').showModal();};td.append(b);tr.append(td);$('rows').append(tr);}}
const statusNames={pending:'Gönderim bekliyor',sending:'Gönderiliyor',sent:'FCM kabul etti',received:'Telefonda alındı',preview:'Tarayıcı denemesi',failed:'Gönderim hatası',expired:'Süresi doldu',cancelled:'Takip değişti / kaldırıldı',superseded:'Daha yeni fiyat var'};
async function load(){if(busy)return;busy=true;try{const [catalogue,status]=await Promise.all([api('/api/catalogue'),api('/api/admin/status')]);items=catalogue.items;render();$('mealCount').textContent=items.length;$('deviceCount').textContent=status.devices.length;$('receivedCount').textContent=status.counts.received||0;$('firebase').textContent=status.firebase_configured?'Firebase ayarları mevcut':'Firebase kurulumu bekleniyor';$('firebaseText').textContent=status.firebase_configured?'Gerçek teslimi bir fiyat değişikliği ve telefonla sınayacağız.':'Fiyat geçmişi ve takipler çalışır. Telefon bildirimi için ücretsiz Firebase projesi ve Android uygulaması eşleştirmesi gerekli.';$('lan').textContent=status.lan_enabled?'Sunucu: '+status.lan_addresses.filter(x=>x!=='127.0.0.1').map(x=>`http://${x}:${status.port}`).join(' veya '):'Şu an yalnızca bilgisayarda açık. Telefon testi için telefonla-baslat.ps1 kullanılmalı.';$('devices').replaceChildren();status.devices.forEach(d=>$('devices').append(el('p',d.name+' · '+(d.push_ready?'Bildirim cihaz kaydı var':'Telefon bildirim kaydı bekleniyor'))));$('events').replaceChildren();if(!status.recent.length)$('events').textContent='Henüz bildirim işlemi yok.';for(const e of status.recent){const meal=items.find(x=>x.id===e.meal_id);const line=el('p',(meal?.name||e.meal_id)+' · '+(statusNames[e.status]||e.status)+(e.last_error?' · '+e.last_error:''));line.className='small';$('events').append(line);}}catch(e){$('status').textContent=e.message;}finally{busy=false;}}
$('priceForm').onsubmit=async e=>{e.preventDefault();$('save').disabled=true;try{const r=await api('/api/admin/price',{meal_id:selected.id,price_minor:Math.round(Number($('price').value)*100),version:selected.version,request_id:requestId});$('priceDialog').close();$('status').textContent=r.changed?`Fiyat kaydedildi. ${r.queued} takip için bildirim kaydı oluştu. Telefon teslimini aşağıdan kontrol et.`:r.repeated?'Bu değişiklik zaten kaydedilmişti.':'Fiyat aynı; yeni kayıt ve bildirim oluşturulmadı.';await load();}catch(e){$('error').textContent=e.message;}finally{$('save').disabled=false;}};
$('pair').onclick=async()=>{try{const r=await api('/api/admin/pair-code',{});$('pairCode').textContent=r.code;$('pairHint').textContent='10 dakika geçerli · bir telefon için tek kullanımlık';}catch(e){$('pairHint').textContent=e.message;}};
$('close').onclick=()=>$('priceDialog').close();$('search').oninput=render;$('refresh').onclick=load;load();setInterval(()=>{if(!document.hidden&&!$('priceDialog').open)load();},5000);
