'use strict';
const $=id=>document.getElementById(id), money=n=>new Intl.NumberFormat('tr-TR',{style:'currency',currency:'TRY'}).format(n/100);
const date=n=>new Date(n*1000).toLocaleString('tr-TR');
const el=(tag,cls,text)=>{const x=document.createElement(tag);x.className=cls||'';if(text!==undefined)x.textContent=text;return x;};
let data=null,mode='budget',selected=null,offline=false,busy=false;
async function api(path,body){const r=await fetch(path,{method:body?'POST':'GET',headers:{'X-Ogun-Lab':'1',...(body?{'Content-Type':'application/json'}:{})},body:body?JSON.stringify(body):undefined});const j=await r.json();if(!r.ok)throw Error(j.error||'İstek başarısız');return j;}
function render(){
 const q=$('search').value.toLocaleLowerCase('tr-TR'),cat=$('category').value,budget=Number($('budget').value)*100;
 $('budgetField').hidden=mode!=='budget';for(const [id,m] of [['budgetTab','budget'],['dropTab','drop'],['watchTab','watch']])$(id).setAttribute('aria-pressed',String(mode===m));
 const filtered=(data?.items||[]).filter(x=>(!q||(x.name+' '+x.branch).toLocaleLowerCase('tr-TR').includes(q))&&(!cat||x.category===cat)&&(mode==='budget'?x.price_minor<=budget:mode==='watch'?x.watch:!offline&&x.drop?.active&&x.drop.big));
 filtered.sort((a,b)=>mode==='drop'?b.drop.saved_minor-a.drop.saved_minor:a.price_minor-b.price_minor);
 $('count').textContent=filtered.length+(mode==='drop'?' büyük fiyat düşüşü':mode==='watch'?' takip edilen yemek':' yemek');$('empty').hidden=!!filtered.length;$('cards').replaceChildren();
 for(const x of filtered){const c=el('article','card');c.append(el('div','meta',x.category+' · '+x.portion),el('h3','',x.name),el('div','meta',x.branch));if(x.drop?.active&&x.drop.big&&!offline)c.append(el('p','drop',`%${x.drop.percent} · ${money(x.drop.saved_minor)} düşüş`));c.append(el('div','price',money(x.price_minor)),el('p','small muted','Son değişiklik: '+date(x.changed_at)));if(x.watch)c.append(el('p','small',x.watch.mode==='target'?'Hedefin: '+money(x.watch.target_minor):x.watch.mode==='big'?'Takip: büyük düşüş':'Takip: her düşüş'));const actions=el('div','actions');const track=el('button','primary',x.watch?'Takibi düzenle':'Takip et');track.onclick=()=>openWatch(x);const hist=el('button','','Fiyat geçmişi');hist.onclick=()=>history(x);actions.append(track,hist);c.append(actions);$('cards').append(c);}
}
async function load(){if(busy)return;busy=true;try{data=await api('/api/catalogue');offline=false;localStorage.setItem('ogun-lab-cache',JSON.stringify(data));const cats=[...new Set(data.items.map(x=>x.category))];if($('category').options.length===1)cats.forEach(c=>$('category').append(new Option(c,c)));$('status').textContent='Kendi deneme veritabanımız · son okuma '+new Date().toLocaleTimeString('tr-TR');const inbox=await api('/api/inbox');const latest=inbox.items[0];$('alerts').hidden=!latest;if(latest){const p=JSON.parse(latest.payload);$('alerts').textContent='TARAYICI DENEME UYARISI · '+p.body+' ('+date(latest.created_at)+') · Bu bir telefon teslim onayı değildir.';}}catch(e){offline=true;if(!data){try{data=JSON.parse(localStorage.getItem('ogun-lab-cache'));}catch{}}$('status').textContent='Bağlantı yok. Son kayıtlar gösteriliyor; aktif fırsatlar ve yeni uyarılar durduruldu.';$('alerts').hidden=true;}finally{busy=false;render();}}
function openWatch(x){selected=x;$('watchTitle').textContent=x.name;$('watchBranch').textContent=x.branch;$('watchMode').value=x.watch?.mode||'any';$('target').value=(x.watch?.target_minor||x.price_minor)/100;$('targetField').hidden=$('watchMode').value!=='target';$('removeWatch').hidden=!x.watch;$('watchError').textContent='';$('watchDialog').showModal();}
$('watchMode').onchange=()=>{$('targetField').hidden=$('watchMode').value!=='target';};
$('watchForm').onsubmit=async e=>{e.preventDefault();$('saveWatch').disabled=true;try{await api('/api/watch',{meal_id:selected.id,mode:$('watchMode').value,target_minor:Math.round(Number($('target').value)*100)});$('watchDialog').close();await load();}catch(e){$('watchError').textContent=e.message;}finally{$('saveWatch').disabled=false;}};
$('removeWatch').onclick=async()=>{try{await api('/api/watch',{meal_id:selected.id,remove:true});$('watchDialog').close();await load();}catch(e){$('watchError').textContent=e.message;}};
async function history(x){$('historyTitle').textContent=x.name;$('historyRows').textContent='Yükleniyor…';$('historyDialog').showModal();try{const h=await api('/api/history/'+encodeURIComponent(x.id));$('historyRows').replaceChildren();h.items.forEach(r=>{const line=el('div','history');line.append(el('span','',date(r.changed_at)),el('strong','',money(r.price_minor)));$('historyRows').append(line);});}catch(e){$('historyRows').textContent=e.message;}}
$('closeWatch').onclick=()=>$('watchDialog').close();$('closeHistory').onclick=()=>$('historyDialog').close();
for(const [id,m] of [['budgetTab','budget'],['dropTab','drop'],['watchTab','watch']])$(id).onclick=()=>{mode=m;render();};
['search','category','budget'].forEach(id=>$(id).addEventListener('input',render));$('refresh').onclick=load;load();setInterval(()=>{if(!document.hidden&&!$('watchDialog').open)load();},5000);
